### PR TITLE
fix(patch): fix #744, add namespace to load patch name

### LINKED ISSUE #773: Zone errors replace filename in stacktrace to [angular]
Currently I'm using Rollbar service for crash reporting. It uses pre-uploaded sourcemaps to parse exception statcktraces. Zone replaces filename in stacktrace with `[angular]` and Rollbar fails to translate it to actual source lines. Currently I have to manually extract `originalStack`  before submitting. I wonder if this replacement is really needed?

Original error translated:
```
Error: Rolbar test
File "webpack:///./~/zone.js/dist/zone.js" line 915 col 1 in ZoneAwareError
var error = NativeError.apply(this, arguments);
File "webpack:///./Spa_Source/app/main/header/header.component.ts" line 40 col 15 in Header.onSelect
throw new Error('Rolbar test');
File "ng:///AppModule/Header.ngfactory.js" line 114 col 24 in Object.eval [as handleEvent]
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 11799 col 86 in Object._ [as handleEvent]
var /** @type {?} */ handleEvent = function (view, nodeIndex, eventName, event) { return ((((...
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 12419 col 68 in Object.handleEvent
handleEvent: function (view, nodeIndex, eventName, event) { return view.def.handleEvent(v...
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 8773 col 1 in dispatchEvent
return Services.handleEvent(view, nodeIndex, eventName, event);
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 10638 col 30 in [anonymous]
return function (event) { return dispatchEvent(view, index, eventName, event); };
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 3840 col 35 in SafeSubscriber.i [as _next]
function (value) { generatorOrNext(value); };
File "webpack:///./~/rxjs/Subscriber.js" line 236 col 1 in SafeSubscriber.__tryOrUnsub
fn.call(this._context, value);
File "webpack:///./~/rxjs/Subscriber.js" line 185 col 1 in SafeSubscriber.next
this.__tryOrUnsub(this._next, value);
File "webpack:///./~/rxjs/Subscriber.js" line 125 col 1 in Subscriber._next
this.destination.next(value);
File "webpack:///./~/rxjs/Subscriber.js" line 89 col 1 in Subscriber.next
this._next(value);
File "webpack:///./~/rxjs/Subject.js" line 55 col 1 in EventEmitter.Subject.next
copy[i].next(value);
File "webpack:///./~/@angular/core/@angular/core.es5.js" line 3814 col 53 in EventEmitter.emit
EventEmitter.prototype.emit = function (value) { _super.prototype.next.call(this, value); };
File "webpack:///./Spa_Source/app/main/header/menu/header.menu.component.ts" line 52 col 23 in HeaderMenu.onItemClick
this.selected.emit(item);
```
Zone wrapped error translated:
```
Error: Rolbar test
File "[angular]" line (unknown) in Header.onSelect (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:1952491)
File "[angular]" line (unknown) in Object.eval [as handleEvent] (ng:///AppModule/Header.ngfactory.js:114:24)
File "[angular]" line (unknown) in Object._ [as handleEvent] (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:50186)
File "[angular]" line (unknown) in Object.handleEvent (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:58606)
File "[angular]" line (unknown) in dispatchEvent (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:23025)
File "[angular]" line (unknown) in http://site/Spa_Dist/main.js?636294494840000000=2164285:1:36518
File "[angular]" line (unknown) in SafeSubscriber.i [as _next] (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:98744)
File "[angular]" line (unknown) in SafeSubscriber.__tryOrUnsub (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:170229)
File "[angular]" line (unknown) in SafeSubscriber.next (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:169424)
File "[angular]" line (unknown) in Subscriber._next (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:168433)
File "[angular]" line (unknown) in Subscriber.next (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:168049)
File "[angular]" line (unknown) in EventEmitter.Subject.next (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:261622)
File "[angular]" line (unknown) in EventEmitter.emit (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:98192)
File "[angular]" line (unknown) in HeaderMenu.onItemClick (http://site/Spa_Dist/main.js?636294494840000000=2164285:1:1953583)
```

### PR DESCRIPTION
**Pull request by JiaLiPassion**
1. patch node's timer setTimeout with `node_timer` name
2. patch `fs` and `events` of nodejs with `Zone.__load_patch` function
3. make some modification for file structure, zone-node will also have a `rollup-main`, so we have a clear structure.

- common (toString, error, promise)
- browser
- node
- mix(electron)

### CODE REVIEW

File: lib/node/node.ts [hunk 1]
```diff
@@ -43,6 +43,12 @@ Zone.__load_patch('timers', (global: any, Zone: ZoneType, api: _ZonePrivate) =>
     // timers module not exists, for example, when we using nativescript
     // timers is not available
   }
+  if (isMix) {
+    // if we are in mix environment, such as Electron,
+    // the global.setTimeout has already been patched,
+    // so we just patch timers.setTimeout
+    return;
```
Comment (thymikee) [inline lib/node/node.ts]: @JiaLiPassion can you explain how global.setTimeout is patched already? I'm using Zone in mixed environment (Jest with jsdom), and I apparently need `global.setTimeout` to be patched, so `fakeAsync` from Angular test utils can work properly. But because it exits early, [this line](https://github.com/angular/zone.js/pull/774/files#diff-46621d39c83a1870b98f0b3e549daacaR56) is not reached.

This very line essentially breaks Angular testing with `fakeAsync` in Jest. We're tracking this under https://github.com/thymikee/jest-preset-angular/issues/65.

Any help appreciated.

**Comment by JiaLiPassion** [comment]
@thymikee , I will check your repo, in `mix` environment, the `timer` will be patched through `browser`, https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts#L30.

**Comment by thymikee** [comment]
@JiaLiPassion thank you for the answer! I was using `dist/zone-node.js` because `jsdom` (simulating browser env) had a bug which had me to fallback from `dist/zone.js`. Seems like the issue is now fixed and works with current version.
