### PR TITLE
fix(promise): fix #891, sometimes NativePromise will not ready, and reduce zone.js size

### LINKED ISSUE #891: es6-promise overwrites zone.js
I am not sure exactly which library is exactly responsible for the issue, but if one looks at this line:

https://github.com/stefanpenner/es6-promise/blob/a5838bd94a76e31ad80ac1685bcd0dbc3d8ce963/dist/es6-promise.js#L1133-L1144

One can see that they are expecting
`Object.prototype.toString.call(window.Promise.resolve())` to be `[object Promise]`, but `zone.js` gives `[object Object]`

So, I am wondering, should `es6-promise` (coming from another widget hosted on our page served over their CDN) look for `[object Object]`, or should zone.js have `[object Promise]` for this `toString()`

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #891 
1. sometimes NativePromise will not be fully ready when override global.Promise, we should add check about it.
2. now by default, typescript 2.3 will compile `iterable` and `spread operator` with new polyfill code and will make `dist/zone.js` bigger, and we don't really have to use `iterable` and `spread`, so we use simple loop to reduce the `zone.js` size.

### CODE REVIEW

**Comment by josephliccini** [comment]
@JiaLiPassion just so I understand this a little better, the `core-js/es6/promise` will:
> Lazy load it's prototype

 can you elaborate a little more? Thanks!

File: lib/zone.ts [hunk 1]
```diff
@@ -1320,7 +1320,11 @@ const Zone: ZoneType = (function(global: any) {
     patchOnProperties: noop,
     patchMethod: () => noop,
     setNativePromise: (NativePromise: any) => {
-      nativeMicroTaskQueuePromise = NativePromise.resolve(0);
+      // sometimes NativePromise lazy load it's prototype
```
Comment (josephliccini) [inline lib/zone.ts]: it's => its (typo) :)

**Comment by JiaLiPassion** [comment]
@josephliccini , sure, in `core-js es6.promise`, the initialization of `ES6 Promise` is 

1. the `Promise constructor` was created, https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L166
2. override `global.Promise`
https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L216
3. prepare `Promise.resove` static method.
https://github.com/zloirock/core-js/blob/master/modules/es6.promise.js#L222

So this will cause the error.

File: lib/zone.ts (hunk 1 above)
Comment (JiaLiPassion) [reply lib/zone.ts]: thanks, I will update the comment.

**Comment by josephliccini** [comment]
Got it.  Thank you!!
