### PR TITLE
fix(core): fix #969, should be able to access target/eventName info in onScheduleTask

### LINKED ISSUE #969: Need a way to access target for eventTasks
In newest versions of zone.js task.data.target is removed, is there anyway to access target for eventTasks?

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #969.

Should be able to access `target/eventName/capture` information when using `addEventListener` in `onScheduleTask` callback. 

in `onScheduleTask`.

```javascript
   onScheduleTask: (parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone,
                           task: Task): any => {
            const target = (task.data as any).taskData.target;
            const eventName = (task.data as any).taskData.eventName;
            const capture = (task.data as any).taskData.capture;
            return parentZoneDelegate.scheduleTask(targetZone, task);
    }
```

in `onInvokeTask`, `onCancelTask`.

```javascript
onInvokeTask(
                 parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone, task: Task,
                 applyThis: any, applyArgs: any) {
      const target = (task as any).target;
      const eventName = (task as any).eventName;
      const capture = (task as any).capture;
}
```

it is not consistent because of `performance` concern (don't want to create so many object).

### CODE REVIEW

File: lib/common/events.ts [hunk 1]
```diff
@@ -396,9 +396,16 @@ export function patchEventTarget(
         taskData.isExisting = isExisting;
 
         const data = useGlobalCallback ? OPTIMIZED_ZONE_EVENT_TASK_DATA : null;
+
+        // keep taskData into data to allow onScheduleEventTask to acess the task information
+        (data as any).taskData = taskData;
```
Comment (jahtalab) [inline lib/common/events.ts]: if the `useGlobalCallback` is false, data would be `null` and this line would fail.

Comment (JiaLiPassion) [reply lib/common/events.ts]: @jahtalab, yes, you are right, thank you.

**Comment by jahtalab** [comment]
Is `useGlobalCallback` a configuration option? AFAICS it's always true.
I'm worried about if `useGlobalCallback` is false then the taskData would not be accessible.

**Comment by JiaLiPassion** [comment]
@jahtalab , it is `configurable` when you want to patch some `new API`, but for the `built in` patch, it is always true, and currently it will be `false` in `nodejs` environment and `RTCPeerConnection` patch.

**Comment by jahtalab** [comment]
Thanks @JiaLiPassion ,
Is there any timeline for the next release that could include this fix?

**Comment by JiaLiPassion** [comment]
@jahtalab,  you are welcome and I am not sure the release date.

**Comment by jahtalab** [comment]
Tests are failing because of rxjs changes in exposed API in the newer versions. I had to lock rxjs version to `5.4.2` to make them pass.

**Comment by JiaLiPassion** [comment]
@jahtalab , yes, this is a known issue, the other PR has used the `rxjs 5.5.3` will fix this issue.
