### PR TITLE
fix(core): fix #1153, ZoneTask.toString should always be a string

### LINKED ISSUE #1153: ZoneTask.toString can return a number, which causes problems in Jasmine
If a karma/jasmine test fails due to an unhandled promise rejection, Jasmine's `PrettyPrinter` class throws an exception due to the `ZoneTask.toString` function not returning a string.

See: https://github.com/jasmine/jasmine/issues/1575

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #1153.

### CODE REVIEW

File: lib/zone.ts [hunk 1]
```diff
@@ -1240,7 +1240,7 @@ const Zone: ZoneType = (function(global: any) {
 
     public toString() {
       if (this.data && typeof this.data.handleId !== 'undefined') {
-        return this.data.handleId;
+        return Object.prototype.toString.call(this.data.handleId);
```
Comment (gkalpak) [inline lib/zone.ts]: I don't think this will have the expected behavior, as it will always return `[object Number]`  (which would cause #341 again).
I think it should be `this.data.handleId.toString()` here.

File: test/common/toString.spec.ts [hunk 2]
```diff
@@ -47,3 +47,29 @@ describe('global function patch', () => {
...
+      }
+    });
+    zone.run(() => {
+      const id = setTimeout(() => {});
+      clearTimeout(id);
+      Promise.resolve().then(() => {});
+      expect(typeof macroTask.toString()).toEqual('string');
+      expect(macroTask.toString()).toEqual(id.toString());
+      expect(typeof microTask.toString()).toEqual('string');
+    });
```
Comment (gkalpak) [inline test/common/toString.spec.ts]: I think it would be valueable to also verify that two different macrotasks have different string representations (just in case).

File: lib/zone.ts (hunk 1 above)
Comment (JiaLiPassion) [reply lib/zone.ts]: Yeah, you are right, thanks!

File: test/common/toString.spec.ts (hunk 2 above)
Comment (JiaLiPassion) [reply test/common/toString.spec.ts]: Got it, case added.

**Comment by JiaLiPassion** [comment]
@gkalpak, thanks for the review, I didn't implement the `valueOf` because besides `setTimeout/interval`, other types of  task (microTask, eventTask) may not have some `valid primitive representations`.

File: test/common/toString.spec.ts [hunk 3]
```diff
@@ -47,3 +47,43 @@ describe('global function patch', () => {
...
+      const id2 = setTimeout(() => {});
+      clearTimeout(id2);
+      Promise.resolve().then(() => {});
+      const macroTask1Str = macroTask1.toString();
+      const macroTask2Str = macroTask2.toString();
+      expect(typeof macroTask1Str).toEqual('string');
+      expect(macroTask1Str).toEqual(id1.toString());
+      expect(typeof macroTask2Str).toEqual('string');
+      expect(macroTask2Str).toEqual(id2.toString());
+      if (macroTask1.data && typeof macroTask1.data.handleId === 'number') {
```
Comment (gkalpak) [inline test/common/toString.spec.ts]: Why is this check necessary?

Comment (JiaLiPassion) [reply test/common/toString.spec.ts]: Yeah, the reason is this case will also run in `nodejs` environment, in `nodejs` the `handleId` will be a `TimerObject`, in that case, we will not check their equality.
