### PR TITLE
fix: fluent interface for EventEmitter

### LINKED ISSUE #470: PR #430 Breaks Stream interface in Node.js
PR #430  breaks fluent interface nature of **Node.js** Stream:

To reproduce, uncomment `require("zone.js")`. The code will crash because **createInterface** and **on** do not return _self_ which prevents cascading

``` js
//require("zone.js")
const fs = require("fs")

require('readline').createInterface({
  input: fs.createReadStream('/etc/hosts')
}).on('line', function (line) {
  console.log(line)
}).on('close', function () {
  console.log('done')
});
```

### PR DESCRIPTION
**Pull request by jakubmal**
Fixes #470 by returning self from `addListener`, `on`, `prependListener`, `removeListener` in Node.js.

### CODE REVIEW

File: lib/node/events.ts [hunk 1]
```diff
@@ -9,9 +9,9 @@ const EE_LISTENERS = 'listeners';
 const EE_ON = 'on';
 
 
-const zoneAwareAddListener = makeZoneAwareAddListener(EE_ADD_LISTENER, EE_REMOVE_LISTENER, false, true);
-const zoneAwarePrependListener = makeZoneAwareAddListener(EE_PREPEND_LISTENER, EE_REMOVE_LISTENER, false, true);
-const zoneAwareRemoveListener = makeZoneAwareRemoveListener(EE_REMOVE_LISTENER, false);
+const zoneAwareAddListener = makeZoneAwareAddListener(EE_ADD_LISTENER, EE_REMOVE_LISTENER, false, true, true);
```
Comment (vicb) [inline lib/node/events.ts]: IMO adding a "magic" boolean param is not the best way to to this.

Can you add `makeChainable...` that wraps the underlying method and return self ?

Comment (jakubmal) [inline lib/node/events.ts]: Sure, let me know what you think now!

File: lib/common/utils.ts [hunk 2]
```diff
@@ -363,3 +363,9 @@ export function patchMethod(target: any, name: string,
   return delegate;
 }
 
+export function makeNamedFnChainable(fn: (self: any, args: any[]) => any) {
```
Comment (vicb) [inline lib/common/utils.ts]: - pls move this fn where it is used (ie `events.ts`).
- use arrow fn,
- wouldn't `callAndReturnFirstParam(...)` be more explicit ?

**Comment by percinor** [comment]
https://github.com/angular/universal/issues/568
I  have modified  zonejs23 or 25  util.ts and event.ts  same like  above ,but also error on ng2 universal project . if  i work express+angular2 +mysql ，its no problem , how to solve it , thanks

**Comment by tamascsaba** [comment]
@vicb, jakubmal ??

**Comment by jakubmal** [comment]
Sorry, I was short on time lately, I should be able get this ready this week!

File: lib/common/utils.ts (hunk 2 above)
Comment (jakubmal) [inline lib/common/utils.ts]: I would prefer named functions, because stack trace when debugging, but I've got nothing against good policies!

**Comment by jakubmal** [comment]
All issues addressed! :)

**Comment by jakubmal** [comment]
@alxhub ?

**Comment by spenoir** [comment]
I'm hoping this PR will fix my `TypeError: Cannot read property 'on' of undefined` when using websockets in Angular 2. Has it been released?

**Comment by JiaLiPassion** [comment]
@spenoir, yes this has been released.
