### PR TITLE
fix(core): fix #989, remove unuse code, use shorter name to reduce bundle size

### LINKED ISSUE #989: 3.4kb size regressions between 0.8.16 and 0.8.19
Size of various polyfills.js build for angular.io with zone.js version changing as the only variable:

v0.8.16 = 37259 bytes
v0.8.17 = 38245 bytes
v0.8.18 = 40274 bytes
v0.8.19 = 40684 bytes

3.4kb is a lot of bytes. Is the increase justified? Can we reduce the size and prevent further regressions?

Justification: zone.js is a prolyfill and as such it needs to be downloaded, parsed and evaluated before anything else gets its turn. This makes the size of zone.js a significant contributor to the overall TTI.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #989.
1. remove unused code
2. move `getUserMedia` and `electron` related code to standalone files.
3. use `shorter` variable and function name to reduce bundle size.
now the size of `zone.min.js` will be `38510` or `38955` bytes. (the size will change when I rebuild)

4. add file size check logic in `travis` build.
5. change `func.apply` to `func.call` for better performance.

now I set a `limitation` of `zone.min.js` to `40000` bytes.

@mhevery , please review the idea is ok or not. thank you!

### CODE REVIEW

File: lib/common/utils.ts [hunk 1]
```diff
@@ -11,50 +11,51 @@
  * @suppress {undefinedVars,globalThis,missingRequire}
  */
 
+// issue #989, to reduce bundle size, use short name
+export const a = Object.getOwnPropertyDescriptor;
```
Comment (mhevery) [inline lib/common/utils.ts]: there is no need to have a single char letters here. You can have long names, they will get renamed using uglify. Single letters are hard on readability.

File: lib/common/utils.ts [hunk 2]
```diff
@@ -11,50 +11,51 @@
...
+export const e = Object.create;
+export const f = Array.prototype.slice;
+export const g = 'addEventListener';
+export const h = 'removeEventListener';
+export const i = (Zone as any).s(g);
+export const j = (Zone as any).s(h);
+export const k = 'true';
+export const l = 'false';
+export const m = '__zone_symbol__';
+export const n = 'function';
```
Comment (mhevery) [inline lib/common/utils.ts]: i think `typeof x == 'string` is faster than `typeof x == STRING_CONST`. That is because in one case the jitter can create the check code which directly checks type to be string, in tho other case it has to generate a more complex code which could be actual type and than compare it to the constant. I would revert this.

File: lib/browser/define-property.ts [hunk 3]
```diff
@@ -41,7 +38,8 @@ export function propertyPatch() {
   };
 
   Object.create = <any>function(obj: any, proto: any) {
-    if (typeof proto === OBJECT && !Object.isFrozen(proto)) {
+    // o is 'object' string
```
Comment (alfaproject) [inline lib/browser/define-property.ts]: `o`?

File: lib/browser/property-descriptor.ts [hunk 4]
```diff
@@ -265,21 +265,19 @@ export function propertyDescriptorPatch(api: _ZonePrivate, _global: any) {
     return;
   }
 
-  const supportsWebSocket = typeof WebSocket !== 'undefined';
+  const supportsWebSocket = typeof WebSocket !== o;
   if (canPatchViaPropertyDescriptor()) {
     const ignoreProperties: IgnoreProperty[] = _global.__Zone_ignore_on_properties;
     // for browsers that we can patch the descriptor:  Chrome & Firefox
     if (isBrowser) {
+      const w: any = window;
```
Comment (mhevery) [inline lib/browser/property-descriptor.ts]: local vars get renamed. Calling it `w` makes it hard to read. Could we call it `window` and that way we don't have to change the code bellow? I know `window = window` would not work, but something like that?

File: lib/common/utils.ts [hunk 5]
```diff
@@ -11,50 +11,72 @@
  * @suppress {undefinedVars,globalThis,missingRequire}
  */
 
+// issue #989, to reduce bundle size, use short name
```
Comment (alfaproject) [inline lib/common/utils.ts]: You shouldn't do the job of a compressor.
In fact, you are probably adding entropy.

P.S.: all of these extra imports/exports add up to browser parsing/interpreting time as well

File: lib/zone.ts [hunk 6]
```diff
@@ -1338,7 +1343,19 @@ const Zone: ZoneType = (function(global: any) {
     return '__zone_symbol__' + name;
   }
 
-
   performanceMeasure('Zone', 'Zone');
+  const z: any = Zone.prototype;
+  z.w = z.wrap;
```
Comment (mhevery) [inline lib/zone.ts]: I would prefer that we don't pollute the Zone public API with these short names. I realized they are not part of `.d.ts` but they will show up in debugger.

How about this idea
`Zone.current` could be replaced with `getZoneCurrent()` which is declared in `util` file. The uglify will rename the `getZoneCurrent` to something short like `x`.

`Zone.current.wrap(...)` could be `wrapWithCurrentZone(...)`

and so on. What do you think?

File: lib/zone.ts [hunk 7]
```diff
@@ -1338,7 +1343,19 @@ const Zone: ZoneType = (function(global: any) {
...
+  z.f = z.fork;
+  z.r = z.run;
+  z.rg = z.runGuarded;
+  z.rt = z.runTask;
+  z.st = z.scheduleTask;
+  z.sc = z.scheduleMacroTask;
+  z.si = z.scheduleMicroTask;
+  z.se = z.scheduleEventTask;
+  z.ct = z.cancelTask;
+  (Zone as any).l = Zone.__load_patch;
```
Comment (mhevery) [inline lib/zone.ts]: same thing here, helpers in `util.ts` can hide the long name without loosing readability

File: lib/browser/property-descriptor.ts (hunk 4 above)
Comment (JiaLiPassion) [reply lib/browser/property-descriptor.ts]: yes, you are right, I have changed the variable to `internalWindow`.

File: lib/common/utils.ts (hunk 1 above)
Comment (JiaLiPassion) [reply lib/common/utils.ts]: Thanks for pointing out this one, I have misunderstanding about uglfiyjs, I have changed the variable name to long names.

File: lib/common/utils.ts (hunk 2 above)
Comment (JiaLiPassion) [reply lib/common/utils.ts]: Got it, I have reverted all `typeof x ===` parts.

File: lib/zone.ts (hunk 6 above)
Comment (JiaLiPassion) [reply lib/zone.ts]: Yes, this is a better solution, I will create those helper functions.

File: lib/zone.ts (hunk 7 above)
Comment (JiaLiPassion) [reply lib/zone.ts]: Got it.

File: lib/browser/define-property.ts (hunk 3 above)
Comment (JiaLiPassion) [reply lib/browser/define-property.ts]: yes, I have reverted this one, thank you!

File: lib/common/utils.ts (hunk 5 above)
Comment (JiaLiPassion) [reply lib/common/utils.ts]: Yes, you are right, I have misunderstanding about uglifyjs, I have modified the PR.

**Comment by IgorMinar** [comment]
awesome! thanks!
