### PR TITLE
Fix #546, #554, #555, the error should keep prototype chain and can be called without new

### LINKED ISSUE #546: v0.7+ - custom Error classes do not work as expected
**Zone.js version:** 0.7.2

**Setup:**
```JavaScript
class MyError extends Error {}
let error = new MyError();
console.log(error instanceof MyError);
```

**Expected:** logs `true`
**Actual:** logs `false` - `error` is an instance of `Error`, rather than `MyError` when zone.js is loaded in the app.

**Demo:** https://plnkr.co/edit/kSKVeuhIrMcluK1D9JSl?p=preview 
Look in the console to see the erroneous behaviour, and then comment out the script tag including zone.js; and the correct behaviour will be observed in the console.

Replacing the version in the <script> tag with 0.6.26 in the above Plunker demo demonstrates correct behaviour - so this bug was introduced with v0.7+ it seems.

### PR DESCRIPTION
**Pull request by JiaLiPassion**
With the commit #547, the #546, error prototype issue was fixed, but a bigger issue occurs, that
Error object can be created with direct call.

let error = Error('message');
And the #547 PR will break it, cause a lot of errors, such as #554, #555

Sorry for the buggy commit in #547.

In this new PR, I checked the this exists or not and checked the this is global or not (non strict mode). So it should fix both #546 and #554, #555.

Please review, Thank you.

### CODE REVIEW

**Comment by mhevery** [comment]
This was reverted on re-opened because one can call `Error` without the `new` operator. This PR breaks that.

File: lib/zone.ts [hunk 1]
```diff
@@ -1352,13 +1363,18 @@ const Zone: ZoneType = (function(global: any) {
...
+      }
     }
-    return error;
-  }
+    return (this && this !== global) ? this : error;
+  };
 
   // Copy the prototype so that instanceof operator works as expected
-  ZoneAwareError.prototype = NativeError.prototype;
+  ZoneAwareError.prototype = Object.create(NativeError.prototype);
```
Comment (mhevery) [inline lib/zone.ts]: Why is `Object.create` necessary here? What is wrong with having it the way it was before?

File: lib/zone.ts [hunk 2]
```diff
@@ -1352,13 +1363,18 @@ const Zone: ZoneType = (function(global: any) {
...
+      if (this && this !== global) {
+        this.stack = this.zoneAwareStack = frames.join('\n');
+      } else {
+        error.stack = error.zoneAwareStack = frames.join('\n');
+        error.originalStack = originalStack;
+      }
     }
-    return error;
-  }
+    return (this && this !== global) ? this : error;
```
Comment (mhevery) [inline lib/zone.ts]: The fact that sometimes we return `this` and sometimes `errror` concerns me. We have two seperate code path and I fear that things will only work in one or the other code path.

File: lib/zone.ts [hunk 3]
```diff
@@ -1318,13 +1318,24 @@ const Zone: ZoneType = (function(global: any) {
   function ZoneAwareError() {
     // Create an Error.
     let error: Error = NativeError.apply(this, arguments);
-
+    if (this && this !== global) {
```
Comment (mhevery) [inline lib/zone.ts]: I think a better strategy would be to always assume that we were called without the `new` operator, that way we don't have to decide.

**Comment by JiaLiPassion** [comment]
@mhevery , Thank you for your review, I'll consider it again and reply to you soon.

**Comment by JiaLiPassion** [comment]
And if we use typescript to write code, current logic is still ok, because typescript will compile 'extends' into 

```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};

var MyError = (function (_super) {
    __extends(MyError, _super);
    function MyError() {
        _super.apply(this, arguments);
    }
    return MyError;
}(Error));
```

But in browser, native implementation, I think the 'extends' may like
```javascript
var MyError = (function (_super) {
    __extends(MyError, _super);
    function MyError() {
        this = new _super(...arguments);
    }
    return MyError;
}(Error));
```
So, in browser, when user call var myError = new MyError(); myError(this) will be the nativeError which was returned from ZoneAwareError, but in typescript version, this is MyError.

I'll continue to do more research.

File: lib/zone.ts (hunk 3 above)
Comment (JiaLiPassion) [inline lib/zone.ts]: Yes, I understand your concern, you are right. I will change it.

File: lib/zone.ts (hunk 2 above)
Comment (JiaLiPassion) [inline lib/zone.ts]: Yes, it is a little risky code, I will modify it.

File: lib/zone.ts (hunk 1 above)
Comment (JiaLiPassion) [inline lib/zone.ts]: I just want to create a new object to let ZoneAwareError.prototype be different with NativeError's, so in the future, if someday modify ZoneAwareError's prototype will not impact NativeError's, for this issue #546, we don't need to use Object.create

**Comment by JiaLiPassion** [comment]
@mhevery , I have changed my PR, please review it is correct or not, Thanks a lot.

File: package.json [hunk 4]
```diff
@@ -69,7 +69,7 @@
     "ts-loader": "^0.6.0",
     "tslint": "^3.15.1",
     "tslint-eslint-rules": "^3.1.0",
-    "typescript": "^2.0.2",
```
Comment (mhevery) [inline package.json]: Let's not upgrade to TS 2.1.4 since we have to make sure that the generated `.d.ts` is compatible with angular which is on alder version on TS. The easiest is to wait until angular is ready.

File: lib/zone.ts [hunk 5]
```diff
@@ -1354,6 +1362,12 @@ const Zone: ZoneType = (function(global: any) {
       }
       error.stack = error.zoneAwareStack = frames.join('\n');
     }
+    // if this is valid, means not undefined
+    // and not global (non-strict mode call Error())
+    // and it is an error not an unrelated object
+    if (this && this !== global && this instanceof Error) {
+      error = setPrototypeOf(error, getPrototypeOf(this));
```
Comment (mhevery) [inline lib/zone.ts]: Calling `setProtypeOf` will make this object slow. Not sure if that is a problem since it is a Error object.

File: package.json (hunk 4 above)
Comment (JiaLiPassion) [inline package.json]: Ok, I see, I will rollback the typescript version.

File: lib/zone.ts (hunk 5 above)
Comment (JiaLiPassion) [inline lib/zone.ts]: Thank you for pointing out this one, I didn't realize that setPrototypeOf will make javascript engine optimization become slow.  how about change the code above to 

```javascript
    // if this is valid, means not undefined
    // and not global (non-strict mode call Error())
    // and it is an error not an unrelated object
    if (this && this !== global && this instanceof Error) {
       Object.assign(error, this);
       return this;
    }
```

-Pro: don't use setPrototypeOf
-Con:if/else will return different object

File: lib/zone.ts [hunk 6]
```diff
@@ -1387,8 +1387,8 @@ const Zone: ZoneType = (function(global: any) {
     // if this is valid, means not undefined
     // and not global (non-strict mode call Error())
     // and it is an error not an unrelated object
-    if (this && this !== global && this instanceof Error
-      && Object.getPrototypeOf(this) !== NativeError.prototype && assignAll(this, error)) {
+    if (this && this !== global && this instanceof Error &&
```
Comment (mhevery) [inline lib/zone.ts]: I was thinking about this some more, and I think the best way to do this would be to place this guard at the top of the function

```
if (! this instanceof ZoneAwareError) {
  return ZoneAwareError.apply(Object.create(ZoneAwareError), arguments);
}
```

This way we force the `new` and only have one code path. What do you think?

Comment (JiaLiPassion) [inline lib/zone.ts]: Thank you for the review, in my understanding, your code will guarantee that 'this' is a valid ZoneAwareError, and we can set all properties from error to this and then return this. Is my understanding correct? 

I have modified the PR based on your idea, please review. Thank you.

**Comment by mhevery** [comment]
Thanks for all of your hard work.
