### PR TITLE
fix(task): fix #832, fix #835, task.data should be an object

### LINKED ISSUE #832: zone.js v0.8.13 Produces Extensive Zone errors in Unit tests-- 'Unhandled Promise rejection:', 'Cannot create property '__creationTrace__'
Using:

- zone.js 0.8.13
- Node 7.10.1
- Angular 4.2.6
- rxjs 5.4.2
- karma 1.7.0
- Typescript 2.3.4

If I use **zone.js 0.8.12** my 111 Client side unit tests  work fine.  After upgrading to **zone.js 0.8.13** I get repeating zone errors as you can see below.

The newest release of zone.js fails extensively on almost all of related Angular unit tests now.  I am seeing this throw two errors:

First one:

```
ERROR: 'Unhandled Promise rejection:', 'Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'', '; Zone:', 'ProxyZone', '; Task:', 'Promise.then', '; Value:', TypeError {longStack: 'TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/long-stack-trace-zone.js?76bd579913a209b82c592a4e9924f4696a01ea6f:115:38)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Zone.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:235:43)
    at Zone.scheduleEventTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:261:25)
    at HTMLDivElement.addEventListener (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:1561:29)
    at DomEventsPlugin.19.DomEventsPlugin.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35817:17)
    at EventManager.19.EventManager.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35155:23)
    at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35676:36)', ngDebugContext: DebugContext_{view: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}, nodeIndex: 0, nodeDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query:..., ngContent: ...}, elDef: Object{index: ..., parent: ..., renderParent: ..., bindingIndex: ..., outputIndex: ..., flags: ..., childFlags: ..., directChildFlags: ..., childMatchedQueries: ..., matchedQueries: ..., matchedQueryIds: ..., references: ..., ngContentIndex: ..., childCount: ..., bindings: ..., bindingFlags: ..., outputs: ..., element: ..., provider: ..., text: ..., query: ..., ngContent: ...}, elView: Object{def: ..., parent: ..., viewContainerParent: ..., parentNodeDef: ..., context: ..., component: ..., nodes: ..., state: ..., root: ..., renderer: ..., oldValues: ..., disposables: ...}}, ngErrorLogger: function () { ... }, __zone_symbol__currentTask: ZoneTask{_zone: Zone{_properties: ..., _parent: ..., _name: ..., _zoneDelegate: ...}, runCount: 0, _zoneDelegates: null, _state: 'notScheduled', type: 'microTask', source: 'Promise.then', data: undefined, scheduleFn: undefined, cancelFn: null, callback: function () { ... }, invoke: function () { ... }}}, 'TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/long-stack-trace-zone.js?76bd579913a209b82c592a4e9924f4696a01ea6f:115:38)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Object.onScheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:404:51)
    at Zone.scheduleTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:235:43)
    at Zone.scheduleEventTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:261:25)
    at HTMLDivElement.addEventListener (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?88b6003995efe175b0ecfca3880d4b42eebe4e32:1561:29)
    at DomEventsPlugin.19.DomEventsPlugin.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35817:17)
    at EventManager.19.EventManager.addEventListener (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35155:23)
    at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (http://localhost:9876/base/ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts?af87a3836823343a258f1bca0af3058ef4b375a6:35676:36)'
```

Second one:

```
Failed: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
	at Object.onScheduleTask (node_modules/zone.js/dist/long-stack-trace-zone.js:115:38)
	at ZoneDelegate.scheduleTask (node_modules/zone.js/dist/zone.js:404:51)
	at Object.onScheduleTask (node_modules/zone.js/dist/zone.js:300:29)
	at ZoneDelegate.scheduleTask (node_modules/zone.js/dist/zone.js:404:51)
	at Zone.scheduleTask (node_modules/zone.js/dist/zone.js:235:43)
	at Zone.scheduleEventTask (node_modules/zone.js/dist/zone.js:261:25)
	at HTMLDivElement.addEventListener (node_modules/zone.js/dist/zone.js:1561:29)
	at DomEventsPlugin.19.DomEventsPlugin.addEventListener (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35817:17)
	at EventManager.19.EventManager.addEventListener (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35155:23)
	at DefaultDomRenderer2.19.DefaultDomRenderer2.listen (ClientSide/test/panels/panel-output-window/panel-output-window.component.spec.ts:35676:36)
```

### LINKED ISSUE #835: Version 0.8.13 crashes with "ReferenceError: _global is not defined"
Updating to 0.8.13 (released yesterday) prevents our Angular application from booting:

    Uncaught ReferenceError: _global is not defined
        at zone.js:1476
        at attachBrowserEvents (index-browser.js:500)
        at new Changes (index-browser.js:515)
        at Object.<anonymous> (index-browser.js:4804)
        at Object.<anonymous> (index-browser.js:12125)
        at __webpack_require__ (bootstrap 6dc1844…:52)
        at Object.44 (main.ts:31)
        at __webpack_require__ (bootstrap 6dc1844…:52)
        at Object.470 (ckeditor.module.ts:22)
        at __webpack_require__ (bootstrap 6dc1844…:52)

### PR DESCRIPTION
**Pull request by JiaLiPassion**
fix #832.
fix #835.

- Task.data should not be a string but an object. 
- should define _global.

### CODE REVIEW

File: lib/common/events.ts [hunk 1]
```diff
@@ -24,6 +29,9 @@ export const ZONE_SYMBOL_PREFIX = '__zone_symbol__';
 
 const EVENT_NAME_SYMBOL_REGX = /^__zone_symbol__(\w+)(true|false)$/;
```
Comment (kgentes) [inline lib/common/events.ts]: since you are already creating TRUE_STR and FALSE_STR on line 10 and line 11, why not reuse those consts here by generating the regex with something like
  `let evt_name_sym_regx = new RegExp('^__zone_symbol__(\\w+)(' +TRUE_STR  + '|' + FALSE_STR + ')\$');`

Comment (JiaLiPassion) [inline lib/common/events.ts]: @kgentes , yes, you are right, I will fix this one. Thank you.

**Comment by JiaLiPassion** [comment]
@kgentes , thank you for review, the code is a little difficult to understand than the earlier version because of the performance concern.

File: lib/common/events.ts (hunk 1 above)
Comment (kgentes) [inline lib/common/events.ts]: agreed.

File: lib/common/events.ts [hunk 2]
```diff
@@ -24,6 +29,9 @@ export const ZONE_SYMBOL_PREFIX = '__zone_symbol__';
...
 
+const _global =
```
Comment (mhevery) [inline lib/common/events.ts]: can we get `global` from `__load_patch`? I would prefer to have the `global` logic centralized.

Comment (JiaLiPassion) [inline lib/common/events.ts]: @mhevery , I have changed the structure and let patchEventTargetMethods to use the `_global` from __load_patch, please review.
